<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DelegationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('delegations')->insert([
            ['id' => 2, 'id_region' => 1, 'delegacion' => 'D-II-59', 'nivel_delegaciona' => 'SECUNDARIA GENERAL', 'sede_delegaciona' => 'PANUCO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'id_region' => 2, 'delegacion' => 'D-III-13', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'TUXPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'id_region' => 2, 'delegacion' => 'D-II-20', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'TUXPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'id_region' => 4, 'delegacion' => 'D-I-77', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'JUCHIQUE DE FERRER', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'id_region' => 2, 'delegacion' => 'D-I-94', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'TAMIAHUA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'id_region' => 6, 'delegacion' => 'D-I-08', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'CARDEL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'id_region' => 2, 'delegacion' => 'D-I-09', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'CERRO AZUL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'id_region' => 2, 'delegacion' => 'D-II-22', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'NARANJOS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'id_region' => 7, 'delegacion' => 'D-II-31', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'COSCOMATEPEC', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'id_region' => 1, 'delegacion' => 'D-II-35', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'TANTOYUCA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'id_region' => 2, 'delegacion' => 'D-II-53', 'nivel_delegaciona' => 'ESCUELA SECUENDARIA Y BACHILLERATO ABIERTO', 'sede_delegaciona' => 'TUXPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'id_region' => 2, 'delegacion' => 'D-I-57', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'TUXPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'id_region' => 2, 'delegacion' => 'D-I-35', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'NARANJOS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'id_region' => 2, 'delegacion' => 'D-I-19', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'CHONTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'id_region' => 2, 'delegacion' => 'D-I-38', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'OZULUAMA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'id_region' => 1, 'delegacion' => 'D-I-71', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'BENITO JUAREZ ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'id_region' => 2, 'delegacion' => 'D-I-80', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'TUXPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 19, 'id_region' => 1, 'delegacion' => 'D-II-50', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'TEMPOAL ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 20, 'id_region' => 4, 'delegacion' => 'D-II-34', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'MISANTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 21, 'id_region' => 5, 'delegacion' => 'D-I-60', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 22, 'id_region' => 6, 'delegacion' => 'D-I-43', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'PIEDRAS NEGRAS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 23, 'id_region' => 4, 'delegacion' => 'D-I-93', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'VEGA DE LA TORRE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 24, 'id_region' => 4, 'delegacion' => 'D-III-15', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'MARTINEZ DE LA TORRE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 25, 'id_region' => 9, 'delegacion' => 'D-II-12', 'nivel_delegaciona' => 'SECUNDARIA Y BACHILLERES', 'sede_delegaciona' => 'TLACOTALPAN ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 26, 'id_region' => 4, 'delegacion' => 'D-I-74', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'TLAPACOYAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 27, 'id_region' => 4, 'delegacion' => 'D-II-32', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'MARTINEZ DE LA TORRE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 28, 'id_region' => 4, 'delegacion' => 'D-II-42', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' => 'MARTINEZ DE LA TORRE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 29, 'id_region' => 1, 'delegacion' => 'D-II-37', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' => 'TANTOYUCA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 30, 'id_region' => 4, 'delegacion' => 'D-II-48', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'SAN RAFAEL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 31, 'id_region' => 4, 'delegacion' => 'D-I-30', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'MARTINEZ DE LA TORRE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 32, 'id_region' => 4, 'delegacion' => 'D-I-33', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'MISANTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 33, 'id_region' => 9, 'delegacion' => 'D-II-14', 'nivel_delegaciona' => 'BACHILLERATO ABIERTOABIERTA', 'sede_delegaciona' => 'ALVARADO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 34, 'id_region' => 6, 'delegacion' => 'D-I-58', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 35, 'id_region' => 6, 'delegacion' => 'D-III-18', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'CARDEL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 36, 'id_region' => 9, 'delegacion' => 'D-I-79', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'ALVARADO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 37, 'id_region' => 7, 'delegacion' => 'D-I-23', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'HUATUSCO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 38, 'id_region' => 5, 'delegacion' => 'D-II-58', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 39, 'id_region' => 7, 'delegacion' => 'D-I-66', 'nivel_delegaciona' => 'FORANEAS', 'sede_delegaciona' => 'CORDOBA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 40, 'id_region' => 4, 'delegacion' => 'D-I-88', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'MARTINEZ DE LA TORRE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 41, 'id_region' => 8, 'delegacion' => 'D-I-78', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'ORIZABA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 42, 'id_region' => 10, 'delegacion' => 'D-I-48', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'SAN ANDRES TUXTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 43, 'id_region' => 7, 'delegacion' => 'D-I-36', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'OMEALCA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 44, 'id_region' => 7, 'delegacion' => 'D-I-14', 'nivel_delegaciona' => 'LOCALES', 'sede_delegaciona' => 'CORDOBA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 45, 'id_region' => 10, 'delegacion' => 'D-I-25', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'ISLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 46, 'id_region' => 9, 'delegacion' => 'D-II-29', 'nivel_delegaciona' => 'NORMAL', 'sede_delegaciona' => 'TLACOTALPAN ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 47, 'id_region' => 10, 'delegacion' => 'D-II-16', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'SAN ANDRES TUXTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 48, 'id_region' => 5, 'delegacion' => 'D-I-84', 'nivel_delegaciona' => 'TECNICOS DOCENTES ADMINISTRATIVOS', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 49, 'id_region' => 10, 'delegacion' => 'D-I-45', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'PLAYA VICENTE ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 50, 'id_region' => 10, 'delegacion' => 'D-II-28', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'ISLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 51, 'id_region' => 9, 'delegacion' => 'D-II-10', 'nivel_delegaciona' => 'SECUNDARIA Y BACHILLERES', 'sede_delegaciona' => 'ALVARADO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 52, 'id_region' => 9, 'delegacion' => 'D-I-63', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'COSAMALOAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 53, 'id_region' => 10, 'delegacion' => 'D-I-29', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'LERDO DE TEJADA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 54, 'id_region' => 10, 'delegacion' => 'D-I-89', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'ISLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 55, 'id_region' => 10, 'delegacion' => 'D-II-51', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'SANTIAGO TUXTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 56, 'id_region' => 10, 'delegacion' => 'D-I-68', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'SANTIAGO TUXTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 57, 'id_region' => 8, 'delegacion' => 'D-I-37', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'ORIZABA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 58, 'id_region' => 5, 'delegacion' => 'D-III-04', 'nivel_delegaciona' => 'ADMINISTRATIVOSEDUCACION FISICA', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 59, 'id_region' => 5, 'delegacion' => 'D-II-21', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 60, 'id_region' => 7, 'delegacion' => 'D-II-09', 'nivel_delegaciona' => 'ESCUELA SECUNDARIA Y BACHILLERES DE ARTES Y OFICIOS', 'sede_delegaciona' => 'CORDOBA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 61, 'id_region' => 5, 'delegacion' => 'D-II-46', 'nivel_delegaciona' => 'TELEBACHILLERATO II', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 62, 'id_region' => 10, 'delegacion' => 'D-I-41', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'SAN ANDRES TUXTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 63, 'id_region' => 8, 'delegacion' => 'D-I-65', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'ZONGOLICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 64, 'id_region' => 8, 'delegacion' => 'D-I-55', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'SAN JUAN TEXHUACAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 65, 'id_region' => 8, 'delegacion' => 'D-I-10', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'CIUDAD MENDOZA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 66, 'id_region' => 8, 'delegacion' => 'D-I-54', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'TEQUILA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 67, 'id_region' => 5, 'delegacion' => 'D-III-01', 'nivel_delegaciona' => 'MANUALES', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 68, 'id_region' => 7, 'delegacion' => 'D-III-11', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'CORDOBA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 69, 'id_region' => 5, 'delegacion' => 'D-I-05', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'ALTOTONGA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 70, 'id_region' => 5, 'delegacion' => 'D-I-92', 'nivel_delegaciona' => 'ENSEÃ‘ANZAS MUSICALES', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 71, 'id_region' => 1, 'delegacion' => 'D-I-90', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'TANTOYUCA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 72, 'id_region' => 1, 'delegacion' => 'D-I-87', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'IXCATEPEC ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 73, 'id_region' => 8, 'delegacion' => 'D-II-17', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' =>  '  ORIZABA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 74, 'id_region' => 8, 'delegacion' => 'D-II-26', 'nivel_delegaciona' => 'TELEBACHILLERATO ', 'sede_delegaciona' =>  '  ORIZABA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 75, 'id_region' => 8, 'delegacion' => 'D-I-03', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  ACULTZINGO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 76, 'id_region' => 9, 'delegacion' => 'D-II-27', 'nivel_delegaciona' => 'TELEBACHILLERATO ', 'sede_delegaciona' =>  '  TIERRA BLANCA  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 77, 'id_region' => 8, 'delegacion' => 'D-III-05 ', 'nivel_delegaciona' => 'EDUCACION FISICA ', 'sede_delegaciona' =>  '  ORIZABA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 78, 'id_region' => 1, 'delegacion' => 'D-I-91', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' =>  '  PANUCO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 79, 'id_region' => 1, 'delegacion' => 'D-I-44', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  PLATON SANCHEZ ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 80, 'id_region' => 5, 'delegacion' => 'D-III-16 ', 'nivel_delegaciona' => 'EDUCACION FISICA ', 'sede_delegaciona' =>  '  COATEPEC  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 81, 'id_region' => 7, 'delegacion' => 'D-I-64', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' =>  '  CORDOBA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 82, 'id_region' => 5, 'delegacion' => 'D-II-38', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 83, 'id_region' => 5, 'delegacion' => 'D-II-13', 'nivel_delegaciona' => 'NORMAL', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 84, 'id_region' => 1, 'delegacion' => 'D-I-51', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  TANTOYUCA  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 85, 'id_region' => 5, 'delegacion' => 'D-II-15', 'nivel_delegaciona' => 'BACHILLERATOS VESPERTINOS ', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 86, 'id_region' => 1, 'delegacion' => 'D-I-52', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  TEMPOAL ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 87, 'id_region' => 5, 'delegacion' => 'D-III-08 ', 'nivel_delegaciona' => 'ADMINISTRATIVOS Y DOCENTES DE LA D.G.B.', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 88, 'id_region' => 5, 'delegacion' => 'D-II-24', 'nivel_delegaciona' => 'UNIVERSIDAD PEDAGOGICA VERACRUZANA', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 89, 'id_region' => 6, 'delegacion' => 'D-I-07', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  BOCA DEL RIO  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 90, 'id_region' => 1, 'delegacion' => 'D-I-39', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  PANUCO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 91, 'id_region' => 1, 'delegacion' => 'D-III-17 ', 'nivel_delegaciona' => 'EDUCACION FISICA ', 'sede_delegaciona' =>  '  TANTOYUCA  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 92, 'id_region' => 9, 'delegacion' => 'D-II-43', 'nivel_delegaciona' => 'BACHILLERATO ', 'sede_delegaciona' =>  '  ALVARADO  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 93, 'id_region' => 9, 'delegacion' => 'D-I-06', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  ALVARADO  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 94, 'id_region' => 5, 'delegacion' => 'D-II-03', 'nivel_delegaciona' => 'BACHILLERATO ARTICULO 3Â° DIURNA ', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 95, 'id_region' => 9, 'delegacion' => 'D-I-56', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  TIERRA BLANCA  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 96, 'id_region' => 5, 'delegacion' => 'D-I-81', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' =>  '  COATEPEC  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 97, 'id_region' => 5, 'delegacion' => 'D-I-61', 'nivel_delegaciona' => 'LOCALES', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 98, 'id_region' => 1, 'delegacion' => 'D-I-72', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  PUEBLO VIEJO  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 99, 'id_region' => 5, 'delegacion' => 'D-I-53', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  TEOCELO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 100, 'id_region' => 5, 'delegacion' => 'D-III-03 ', 'nivel_delegaciona' => 'ADMINISTRATIVOS OFICINAS CENTRALES', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 101, 'id_region' => 5, 'delegacion' => 'D-I-11', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  COATEPEC  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 102, 'id_region' => 5, 'delegacion' => 'D-I-34', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  NAOLINCO  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 103, 'id_region' => 5, 'delegacion' => 'D-III-24 ', 'nivel_delegaciona' => 'ADMINISTRATIVOS TELEBACHILLERATO ', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 104, 'id_region' => 5, 'delegacion' => 'D-I-75', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  CARRIZAL  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 105, 'id_region' => 5, 'delegacion' => 'D-III-23 ', 'nivel_delegaciona' => 'EDUCACION FISICA ', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 106, 'id_region' => 5, 'delegacion' => 'D-I-20', 'nivel_delegaciona' => 'PRIMARIAS ', 'sede_delegaciona' =>  '  EMILIANO ZAPATA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 107, 'id_region' => 5, 'delegacion' => 'D-II-04', 'nivel_delegaciona' => 'BACHILLERATOS MATUTINOS', 'sede_delegaciona' =>  '  XALAPA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 108, 'id_region' => 5, 'delegacion' => 'D-IV-18', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' =>  '  ALTOTONGA  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 109, 'id_region' => 2, 'delegacion' => 'D-IV-09', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' =>  '  TUXPAN ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 110, 'id_region' => 4, 'delegacion' => 'D-IV-28', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' =>  '  MISANTLA  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 111, 'id_region' => 4, 'delegacion' => 'D-IV-08', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' =>  '  MARTINEZ DE LA TORRE  ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 112, 'id_region' => 6, 'delegacion' => 'D-IV-05', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' =>  '  SOLEDAD DE DOBLADO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 113, 'id_region' => 10, 'delegacion' => 'D-IV-03', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'SAN ANDRES TUXTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 114, 'id_region' => 10, 'delegacion' => 'D-IV-26', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'ISLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 115, 'id_region' => 9, 'delegacion' => 'D-IV-06', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'COSAMALOAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 116, 'id_region' => 8, 'delegacion' => 'D-IV-32', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'ZONGOLICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 117, 'id_region' => 8, 'delegacion' => 'D-IV-07', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'ORIZABA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 118, 'id_region' => 5, 'delegacion' => 'D-IV-17', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'COATEPEC', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 119, 'id_region' => 7, 'delegacion' => 'D-IV-16', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'CORDOBA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 120, 'id_region' => 9, 'delegacion' => 'D-IV-21', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'ALVARADO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 121, 'id_region' => 5, 'delegacion' => 'D-IV-02', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 122, 'id_region' => 1, 'delegacion' => 'D-IV-13', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'TANTOYUCA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 123, 'id_region' => 4, 'delegacion' => 'C.T.05', 'nivel_delegaciona' => 'ESCUELA Y BACHILLERES ALFONSO REYES', 'sede_delegaciona' => 'MISANTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 124, 'id_region' => 5, 'delegacion' => 'C.T.23', 'nivel_delegaciona' => 'BACHILLERATO JOAQUIN RAMIREZ CABAÃ‘AS MIXTA', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 125, 'id_region' => 4, 'delegacion' => 'C.T.09', 'nivel_delegaciona' => 'SECUNDARIA GENERAL', 'sede_delegaciona' => 'SAN RAFAEL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 126, 'id_region' => 8, 'delegacion' => 'C.T.13', 'nivel_delegaciona' => 'SECUNDARIA', 'sede_delegaciona' => 'CIUDAD MENDOZA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 127, 'id_region' => 4, 'delegacion' => 'C.T.29', 'nivel_delegaciona' => 'BACHILLERATO', 'sede_delegaciona' => 'MARTINEZ DE LA TORRE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 128, 'id_region' => 10, 'delegacion' => 'C.T.36', 'nivel_delegaciona' => 'SECUNDARIA Y BACHILLERATO', 'sede_delegaciona' => 'SANTIAGO TUXTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 129, 'id_region' => 5, 'delegacion' => 'C.T.20', 'nivel_delegaciona' => 'BACHILLEARTO RICARDO FLORES MAGON MIXTO', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 130, 'id_region' => 5, 'delegacion' => 'C.T.03', 'nivel_delegaciona' => 'BACHILLERATO SABATINO', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 131, 'id_region' => 5, 'delegacion' => 'C.T.21', 'nivel_delegaciona' => 'BACHILLERATO ANTONIO MARIA DE RIVERA MIXTA', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 132, 'id_region' => 8, 'delegacion' => 'C.T.14', 'nivel_delegaciona' => 'BACHILLERATO', 'sede_delegaciona' => 'ORIZABA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 133, 'id_region' => 6, 'delegacion' => 'C.T.10', 'nivel_delegaciona' => 'SECUNDARIA', 'sede_delegaciona' => 'SOLEDAD DE DOBLADO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 134, 'id_region' => 8, 'delegacion' => 'C.T.40', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'ZONGOLICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 135, 'id_region' => 6, 'delegacion' => 'C.T.32', 'nivel_delegaciona' => 'SECUNDARIA', 'sede_delegaciona' => 'CARDEL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 136, 'id_region' => 1, 'delegacion' => 'C.T.07', 'nivel_delegaciona' => 'SECUNDARIA GENERAL', 'sede_delegaciona' => 'IXCATEPEC ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 137, 'id_region' => 6, 'delegacion' => 'C.T.31', 'nivel_delegaciona' => 'UNIVERSIDAD PEDAGOGICA VERACRUZANA', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 138, 'id_region' => 5, 'delegacion' => 'C.T.33', 'nivel_delegaciona' => 'NORMAL MANUEL SUAREZ TRUJILLO', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 139, 'id_region' => 5, 'delegacion' => 'C.T.35', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 140, 'id_region' => 5, 'delegacion' => 'C.T.24', 'nivel_delegaciona' => 'DEPARTAMENTO NORMALES', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 141, 'id_region' => 11, 'delegacion' => 'D-I-28', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'JESUS CARRANZA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 142, 'id_region' => 11, 'delegacion' => 'D-I-02', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 143, 'id_region' => 3, 'delegacion' => 'D-II-25', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'ESPINAL ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 144, 'id_region' => 11, 'delegacion' => 'D-I-31', 'nivel_delegaciona' => 'FORANEAS', 'sede_delegaciona' => 'MINATITLAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 145, 'id_region' => 11, 'delegacion' => 'D-I-17', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'COSOLEACAQUE', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 146, 'id_region' => 3, 'delegacion' => 'D-I-26', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'IXHUATLAN DE MADERO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 147, 'id_region' => 1, 'delegacion' => 'D-II-01', 'nivel_delegaciona' => 'NORMAL', 'sede_delegaciona' => 'ACECECA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 148, 'id_region' => 3, 'delegacion' => 'D-I-04', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'ALAMO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 149, 'id_region' => 11, 'delegacion' => 'D-I-01', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 150, 'id_region' => 3, 'delegacion' => 'D-I-83', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'POZA RICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 151, 'id_region' => 7, 'delegacion' => 'D-III-21', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'HUATUSCO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 152, 'id_region' => 7, 'delegacion' => 'D-I-22', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'FORTIN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 153, 'id_region' => 11, 'delegacion' => 'D-I-86', 'nivel_delegaciona' => 'EDUCACION ESPECIAL', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 154, 'id_region' => 3, 'delegacion' => 'D-I-69', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'TIHUATLAN ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 155, 'id_region' => 7, 'delegacion' => 'D-I-16', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'COSCOMATEPEC', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 156, 'id_region' => 3, 'delegacion' => 'D-II-47', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'PAPANTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 157, 'id_region' => 3, 'delegacion' => 'D-III-12', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'POZA RICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 158, 'id_region' => 11, 'delegacion' => 'D-II-44', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 159, 'id_region' => 11, 'delegacion' => 'D-II-52', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' => 'COATZACOALCOS ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 160, 'id_region' => 11, 'delegacion' => 'D-II-23', 'nivel_delegaciona' => 'SECUNDARIA', 'sede_delegaciona' => 'COATZACOALCOS ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 161, 'id_region' => 3, 'delegacion' => 'D-I-24', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'HUAYACOCOTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 162, 'id_region' => 3, 'delegacion' => 'D-I-40', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'PAPANTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 163, 'id_region' => 3, 'delegacion' => 'D-I-21', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'ESPINAL ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 164, 'id_region' => 3, 'delegacion' => 'D-I-85', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'PAPANTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 165, 'id_region' => 3, 'delegacion' => 'D-I-46', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'POZA RICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 166, 'id_region' => 3, 'delegacion' => 'D-I-67', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'GUTIERREZ ZAMORA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 167, 'id_region' => 11, 'delegacion' => 'D-I-12', 'nivel_delegaciona' => 'FORANEAS', 'sede_delegaciona' => 'COATZACOALCOS ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 168, 'id_region' => 3, 'delegacion' => 'D-II-41', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' => 'POZA RICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 169, 'id_region' => 3, 'delegacion' => 'D-II-19', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'ALAMO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 170, 'id_region' => 11, 'delegacion' => 'D-I-49', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'SAYULA DE ALEMAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 171, 'id_region' => 11, 'delegacion' => 'D-I-59', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 172, 'id_region' => 11, 'delegacion' => 'D-II-45', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'COATZACOALCOS ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 173, 'id_region' => 11, 'delegacion' => 'D-III-22', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'COATZACOALCOS ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 174, 'id_region' => 11, 'delegacion' => 'D-I-32', 'nivel_delegaciona' => 'LOCALES', 'sede_delegaciona' => 'MINATITLAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 175, 'id_region' => 1, 'delegacion' => 'D-I-18', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'CHICONTEPEC ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 176, 'id_region' => 3, 'delegacion' => 'D-II-57', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'HUAYACOCOTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 177, 'id_region' => 7, 'delegacion' => 'D-I-76', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'TOTUTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 178, 'id_region' => 7, 'delegacion' => 'D-I-42', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'PASO DEL MACHO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 179, 'id_region' => 9, 'delegacion' => 'D-I-15', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'COSAMALOAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 180, 'id_region' => 9, 'delegacion' => 'D-III-02', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'TIERRA BLANCA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 181, 'id_region' => 2, 'delegacion' => 'D-IV-12', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'NARANJOS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 182, 'id_region' => 11, 'delegacion' => 'D-IV-25', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'MINATITLAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 183, 'id_region' => 11, 'delegacion' => 'D-IV-19', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'COATZACOALCOS ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 184, 'id_region' => 3, 'delegacion' => 'D-IV-10', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'POZA RICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 185, 'id_region' => 3, 'delegacion' => 'D-IV-31', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'TIHUATLAN ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 186, 'id_region' => 3, 'delegacion' => 'D-IV-15', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'PAPANTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 187, 'id_region' => 3, 'delegacion' => 'C.T.01', 'nivel_delegaciona' => 'BACHILLERATO', 'sede_delegaciona' => 'PAPANTLA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 188, 'id_region' => 11, 'delegacion' => 'C.T.30', 'nivel_delegaciona' => 'SECUNDARIA Y BACHILLERATO', 'sede_delegaciona' => 'MINATITLÃN ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 189, 'id_region' => 11, 'delegacion' => 'C.T.25', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 190, 'id_region' => 11, 'delegacion' => 'C.T.26', 'nivel_delegaciona' => 'ESCUELA DE ENFERMERIA', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 228, 'id_region' => 2, 'delegacion' => 'C.T.08', 'nivel_delegaciona' => 'UNIVERSIDAD PEDAGÃ“GICA VERACRUZANA', 'sede_delegaciona' => 'TUXPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 237, 'id_region' => 2, 'delegacion' => 'D-IV-36', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'TAMIAHUA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 238, 'id_region' => 5, 'delegacion' => 'D-I-62', 'nivel_delegaciona' => 'FORANEAS', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 239, 'id_region' => 5, 'delegacion' => 'D-III-14', 'nivel_delegaciona' => 'DOCENTES EDUCACION FISICA', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 240, 'id_region' => 5, 'delegacion' => 'D-II-02', 'nivel_delegaciona' => 'BACHILLERATO ANTONIO MARIA DE RIVERA VESPERTINA', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 241, 'id_region' => 5, 'delegacion' => 'D-III-09', 'nivel_delegaciona' => 'ADMINISTRATIVOS TELEBACHILLERATO', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 242, 'id_region' => 5, 'delegacion' => 'D-II-56', 'nivel_delegaciona' => 'BACHILLERATO ANTONIO MARIA DE RIVERA', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 243, 'id_region' => 5, 'delegacion' => 'D-I-47', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'LAS VIGAS DE RAMIREZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 245, 'id_region' => 9, 'delegacion' => 'D-III-07', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'ALVARADO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 253, 'id_region' => 6, 'delegacion' => 'D-II-05', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 273, 'id_region' => 9, 'delegacion' => 'D-II-30', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'COSAMALOAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 274, 'id_region' => 1, 'delegacion' => 'D-IV-23', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'PANUCO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 276, 'id_region' => 11, 'delegacion' => 'D-I-82', 'nivel_delegaciona' => 'PREESCOLAR', 'sede_delegaciona' => 'MINATITLÃN ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 277, 'id_region' => 7, 'delegacion' => 'C.T.02', 'nivel_delegaciona' => 'SECUNDARIAS', 'sede_delegaciona' => 'HUATUSCO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 280, 'id_region' => 1, 'delegacion' => 'D-II-18', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'CHICONTEPEC ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 281, 'id_region' => 3, 'delegacion' => 'D-II-54', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' => 'ALAMO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 282, 'id_region' => 10, 'delegacion' => 'D-III-19', 'nivel_delegaciona' => 'EDUCACIÃ“N FÃSICA', 'sede_delegaciona' => 'SAN ANDRES TUXTLA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 284, 'id_region' => 6, 'delegacion' => 'C.T.17', 'nivel_delegaciona' => 'UNIVERSIDAD FEMENINA', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 285, 'id_region' => 6, 'delegacion' => 'D-II-40', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 286, 'id_region' => 6, 'delegacion' => 'D-II-49', 'nivel_delegaciona' => 'SECUNDARIA GENERAL', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 287, 'id_region' => 1, 'delegacion' => 'D-IV-11', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'TEMPOAL ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 288, 'id_region' => 1, 'delegacion' => 'D-IV-22', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'CHICONTEPEC ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 289, 'id_region' => 1, 'delegacion' => 'D-IV-35', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'PUEBLO VIEJO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 290, 'id_region' => 1, 'delegacion' => 'D-IV-37', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'PLATON SANCHEZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 291, 'id_region' => 3, 'delegacion' => 'D-II-07', 'nivel_delegaciona' => 'SECUNDARIA Y BACHILLERATO', 'sede_delegaciona' => 'POZA RICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 292, 'id_region' => 3, 'delegacion' => 'D-II-33', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'POZA RICA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 293, 'id_region' => 3, 'delegacion' => 'D-IV-14', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'ALAMO ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 294, 'id_region' => 3, 'delegacion' => 'D-IV-24', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'GUTIERREZ ZAMORA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 295, 'id_region' => 5, 'delegacion' => 'C.T.18', 'nivel_delegaciona' => 'ESCUELA SECUNDARIA EXPERIMENTAL', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 296, 'id_region' => 6, 'delegacion' => 'C.T.06', 'nivel_delegaciona' => 'OFICIAL', 'sede_delegaciona' => 'CARDEL', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 297, 'id_region' => 6, 'delegacion' => 'C.T.11', 'nivel_delegaciona' => 'BACHILLERES OFICIAL', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 298, 'id_region' => 6, 'delegacion' => 'C.T.15', 'nivel_delegaciona' => 'BACHILLERATO NOCTURNO', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 299, 'id_region' => 6, 'delegacion' => 'C.T.22', 'nivel_delegaciona' => 'ESTEBAN M', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 300, 'id_region' => 6, 'delegacion' => 'D-II-06', 'nivel_delegaciona' => 'ILLUSTRE', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 301, 'id_region' => 6, 'delegacion' => 'D-III-06', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 302, 'id_region' => 6, 'delegacion' => 'D-IV-01', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'VERACRUZ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 303, 'id_region' => 6, 'delegacion' => 'D-IV-27', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'BOCA DEL RIO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 304, 'id_region' => 6, 'delegacion' => 'D-IV-30', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'PIEDRAS NEGRAS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 305, 'id_region' => 8, 'delegacion' => 'D-I-27', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'IXTACZOQUITLAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 306, 'id_region' => 8, 'delegacion' => 'D-II-36', 'nivel_delegaciona' => 'SECUNDARIA Y BACHILLERATO DIURNA', 'sede_delegaciona' => 'ORIZABA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 307, 'id_region' => 8, 'delegacion' => 'D-III-10', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'CIUDAD MENDOZA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 308, 'id_region' => 8, 'delegacion' => 'D-IV-04', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'CIUDAD MENDOZA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 309, 'id_region' => 9, 'delegacion' => 'D-I-70', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'TRES VALLES ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 310, 'id_region' => 9, 'delegacion' => 'D-II-08', 'nivel_delegaciona' => 'SECUNDARIA Y BACHILLERATO', 'sede_delegaciona' => 'COSAMALOAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 311, 'id_region' => 9, 'delegacion' => 'D-III-20', 'nivel_delegaciona' => 'EDUCACION FISICA', 'sede_delegaciona' => 'COSAMALOAPAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 312, 'id_region' => 9, 'delegacion' => 'D-IV-29', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'TIERRA BLANCA ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 313, 'id_region' => 9, 'delegacion' => 'D-IV-34', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'TLACOTALPAN ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 314, 'id_region' => 11, 'delegacion' => 'D-I-13', 'nivel_delegaciona' => 'PRIMARIAS LOCALES', 'sede_delegaciona' => 'COATZACOALCOS ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 315, 'id_region' => 11, 'delegacion' => 'D-II-11', 'nivel_delegaciona' => 'SECUNDARIA', 'sede_delegaciona' => 'COATZACOALCOS ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 316, 'id_region' => 11, 'delegacion' => 'D-II-39', 'nivel_delegaciona' => 'TELESECUNDARIA', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 317, 'id_region' => 11, 'delegacion' => 'D-IV-20', 'nivel_delegaciona' => 'JUBILADOS Y PENSIONADOS', 'sede_delegaciona' => 'ACAYUCAN', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 318, 'id_region' => 6, 'delegacion' => 'D-I-50', 'nivel_delegaciona' => 'PRIMARIAS', 'sede_delegaciona' => 'SOLEDAD DE DOBLADO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 332, 'id_region' => 6, 'delegacion' => 'D-I-73', 'nivel_delegaciona' => 'PRIMARIA', 'sede_delegaciona' => 'PASO DE OVEJAS', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 333, 'id_region' => 5, 'delegacion' => 'C.T.04', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'XALAPA', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 334, 'id_region' => 7, 'delegacion' => 'C.T.12', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'HUATUSCO', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 335, 'id_region' => 7, 'delegacion' => 'C.T.16', 'nivel_delegaciona' => 'TELEBACHILLERATO', 'sede_delegaciona' => 'CORDOBA ', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
